-- Sequences

CREATE SEQUENCE Users_UserID_Seq
  START WITH 100
  INCREMENT BY 1;

CREATE SEQUENCE Reservations_ReservationID_Seq
  START WITH 100
  INCREMENT BY 1;

CREATE SEQUENCE Books_BookID_Seq
  START WITH 100
  INCREMENT BY 1;

CREATE SEQUENCE Fines_FineID_Seq
  START WITH 100
  INCREMENT BY 1;

CREATE SEQUENCE Genres_GenreID_Seq
  START WITH 100
  INCREMENT BY 1;

CREATE SEQUENCE Authors_AuthorID_Seq
  START WITH 100
  INCREMENT BY 1;
